# syntax=docker/dockerfile:1.7

ARG TARGETPLATFORM=linux/amd64
ARG BILILIVE_BINARY=bililive-linux-amd64
FROM --platform=$TARGETPLATFORM ubuntu:22.04

ARG TARGETARCH
ARG BILILIVE_BINARY

ENV IS_DOCKER=true
ENV WORKDIR="/srv/bililive"
ENV OUTPUT_DIR="/srv/bililive" \
    CONF_DIR="/etc/bililive-go" \
    PORT=8080

ENV PUID=0 PGID=0 UMASK=022

RUN mkdir -p $OUTPUT_DIR && \
    mkdir -p $CONF_DIR && \
    mkdir -p /opt/bililive/tools && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    libatomic1 \
    tzdata && \
    sh -c '\
    if [ "$TARGETARCH" = "arm" ]; then \
    echo "skip gosu for arm (armv7/armhf)"; \
    else \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gosu; \
    fi' && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ${BILILIVE_BINARY} /usr/bin/bililive-go
COPY config.docker.yml $CONF_DIR/config.yml
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /usr/bin/bililive-go /entrypoint.sh && \
    /usr/bin/bililive-go --sync-built-in-tools-to-path /opt/bililive/tools || true

VOLUME $OUTPUT_DIR

EXPOSE $PORT

WORKDIR ${WORKDIR}
ENTRYPOINT [ "sh" ]
CMD [ "/entrypoint.sh" ]
